'use strict';

const { onRequest } = require('firebase-functions/v2/https');
const PDFDocument   = require('pdfkit');

// ── Colour palette ────────────────────────────────────────────────────────────
const C = {
  brand:    '#0369a1',
  critical: '#dc2626',
  serious:  '#ea580c',
  moderate: '#d97706',
  minor:    '#2563eb',
  pass:     '#16a34a',
  dark:     '#0f172a',
  body:     '#334155',
  mid:      '#64748b',
  light:    '#e2e8f0',
  bg:       '#f8fafc',
};

const IMPACT_ORDER = ['critical', 'serious', 'moderate', 'minor'];

// ── Cloud Function ─────────────────────────────────────────────────────────────
exports.generatePdf = onRequest({ cors: true }, async (req, res) => {
  if (req.method !== 'POST') {
    res.status(405).json({ error: 'Method not allowed' });
    return;
  }

  const {
    url,
    testedAt,
    violations  = [],
    incomplete  = [],
    passCount   = 0,
  } = req.body || {};

  if (!url) {
    res.status(400).json({ error: 'Missing required field: url' });
    return;
  }

  // Sanitise URL into a filename-safe slug
  const slug     = url.replace(/https?:\/\//i, '').replace(/[^a-z0-9]/gi, '-').slice(0, 50);
  const dateSlug = new Date().toISOString().slice(0, 10);
  const filename = `a11y-report-${slug}-${dateSlug}.pdf`;

  // Create the document with buffered pages so we can add footers afterwards
  const doc = new PDFDocument({
    size:        'A4',
    margin:      50,
    bufferPages: true,
    info: {
      Title:    `Accessibility Report — ${url}`,
      Author:   'a11y-check.eu',
      Subject:  'WCAG 2.1 AA Accessibility Audit',
      Creator:  'a11y-check.eu powered by axe-core',
    },
  });

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
  doc.pipe(res);

  const PW  = doc.page.width;           // 595.28 pt
  const PH  = doc.page.height;          // 841.89 pt
  const ML  = 50;                        // left margin
  const W   = PW - ML * 2;              // usable width ≈ 495 pt

  // ── 1. Header ─────────────────────────────────────────────────────────────
  drawHeader(doc, PW, ML, W, url, testedAt);

  // ── 2. Summary stats ──────────────────────────────────────────────────────
  drawSummary(doc, ML, W, violations.length, incomplete.length, passCount);

  // ── 3. Violations ─────────────────────────────────────────────────────────
  sectionHeading(doc, ML, W, `Violations (${violations.length})`);

  if (violations.length === 0) {
    doc
      .fillColor(C.pass)
      .font('Helvetica')
      .fontSize(10)
      .text('✓  No violations found.', ML);
    doc.moveDown(1.2);
  } else {
    const sorted = [...violations].sort(
      (a, b) => IMPACT_ORDER.indexOf(a.impact) - IMPACT_ORDER.indexOf(b.impact),
    );
    for (const rule of sorted) {
      drawRule(doc, rule, ML, W, PH);
    }
  }

  // ── 4. Needs Review ───────────────────────────────────────────────────────
  if (incomplete.length > 0) {
    sectionHeading(doc, ML, W, `Needs Manual Review (${incomplete.length})`);
    doc
      .fillColor(C.mid)
      .font('Helvetica-Oblique')
      .fontSize(9)
      .text(
        'axe-core could not automatically determine if these pass or fail — review them manually.',
        ML,
      );
    doc.moveDown(0.8);
    for (const rule of incomplete) {
      drawRule(doc, rule, ML, W, PH, true);
    }
  }

  // ── 5. Footers (applied to every page after content is finalised) ─────────
  const range = doc.bufferedPageRange();
  for (let i = 0; i < range.count; i++) {
    doc.switchToPage(i);
    const fy = PH - 32;
    doc
      .moveTo(ML, fy - 6)
      .lineTo(ML + W, fy - 6)
      .strokeColor(C.light)
      .lineWidth(0.5)
      .stroke();
    doc
      .fillColor(C.mid)
      .font('Helvetica')
      .fontSize(7.5)
      .text(
        'Generated by a11y-check.eu · WCAG 2.1 AA audit powered by axe-core',
        ML,
        fy,
        { width: W * 0.65 },
      );
    doc.text(`Page ${i + 1} of ${range.count}`, ML, fy, {
      width: W,
      align: 'right',
    });
  }

  doc.end();
});

// ── Helpers ───────────────────────────────────────────────────────────────────

function drawHeader(doc, PW, ML, W, url, testedAt) {
  // Blue background strip
  doc.rect(0, 0, PW, 88).fill(C.brand);

  // Brand + subtitle
  doc
    .fillColor('#ffffff')
    .font('Helvetica-Bold')
    .fontSize(22)
    .text('a11y-check.eu', ML, 20);
  doc
    .font('Helvetica')
    .fontSize(10)
    .text('Accessibility Audit Report', ML, 50);

  // Move cursor below the strip
  doc.y = 106;

  // Audited URL label
  doc.fillColor(C.mid).font('Helvetica').fontSize(8).text('AUDITED URL', ML);
  doc
    .fillColor(C.dark)
    .font('Helvetica-Bold')
    .fontSize(10)
    .text(url, ML, doc.y + 1, { width: W, link: url });

  doc.moveDown(0.55);

  // Tested-at label
  const dateStr = testedAt
    ? new Date(testedAt).toLocaleString('en-GB', {
        dateStyle: 'long',
        timeStyle: 'short',
        timeZone:  'Europe/Brussels',
      })
    : new Date().toLocaleString('en-GB', {
        dateStyle: 'long',
        timeStyle: 'short',
        timeZone:  'Europe/Brussels',
      });

  doc.fillColor(C.mid).font('Helvetica').fontSize(8).text('TESTED AT', ML);
  doc.fillColor(C.dark).font('Helvetica').fontSize(10).text(dateStr, ML);

  doc.moveDown(1.4);
}

function drawSummary(doc, ML, W, vCount, iCount, passCount) {
  const stats = [
    { label: 'Violations',  value: vCount,   color: vCount  > 0 ? C.critical : C.pass },
    { label: 'Need Review', value: iCount,   color: iCount  > 0 ? C.moderate : C.pass },
    { label: 'Passed',      value: passCount, color: C.pass },
  ];

  const boxW = (W - 16) / 3;
  const boxH = 72;
  const y    = doc.y;

  stats.forEach((s, i) => {
    const x = ML + i * (boxW + 8);
    doc.rect(x, y, boxW, boxH).fillAndStroke(C.bg, C.light);
    doc
      .fillColor(s.color)
      .font('Helvetica-Bold')
      .fontSize(30)
      .text(String(s.value), x, y + 8, { width: boxW, align: 'center' });
    doc
      .fillColor(C.mid)
      .font('Helvetica')
      .fontSize(8)
      .text(s.label.toUpperCase(), x, y + 48, { width: boxW, align: 'center' });
  });

  doc.y = y + boxH + 22;
}

function sectionHeading(doc, ML, W, title) {
  doc.moveDown(0.4);
  doc
    .fillColor(C.dark)
    .font('Helvetica-Bold')
    .fontSize(13)
    .text(title, ML);
  doc.moveDown(0.15);
  doc
    .moveTo(ML, doc.y)
    .lineTo(ML + W, doc.y)
    .strokeColor(C.light)
    .lineWidth(1)
    .stroke();
  doc.moveDown(0.7);
}

function drawRule(doc, rule, ML, W, PH, isIncomplete = false) {
  const impact = rule.impact || 'minor';
  const color  = C[impact] || C.mid;

  // Page-break guard
  if (doc.y > PH - 170) {
    doc.addPage();
    doc.y = 60;
  }

  const startY = doc.y;

  // ── Impact badge ──────────────────────────────────────────────────────────
  const bW = 62;
  const bH = 17;
  doc.rect(ML, startY, bW, bH).fill(color);
  doc
    .fillColor('#ffffff')
    .font('Helvetica-Bold')
    .fontSize(7.5)
    .text(impact.toUpperCase(), ML, startY + 5, { width: bW, align: 'center' });

  // ── Description (beside badge) ────────────────────────────────────────────
  doc
    .fillColor(C.dark)
    .font('Helvetica-Bold')
    .fontSize(9.5)
    .text(rule.description, ML + bW + 8, startY, { width: W - bW - 8 });

  doc.moveDown(0.3);

  // ── Element count + help link ─────────────────────────────────────────────
  const nodeLabel = `${rule.nodes.length} element${rule.nodes.length !== 1 ? 's' : ''} affected`;
  const rowY = doc.y;

  doc.fillColor(C.mid).font('Helvetica').fontSize(8.5).text(nodeLabel, ML, rowY);

  if (rule.helpUrl) {
    doc
      .fillColor(C.brand)
      .font('Helvetica')
      .fontSize(8.5)
      .text('How to fix ↗', ML, rowY, {
        width:     W,
        align:     'right',
        link:      rule.helpUrl,
        underline: true,
      });
  }

  doc.moveDown(0.45);

  // ── HTML snippets (up to 3 nodes) ─────────────────────────────────────────
  const nodes = rule.nodes.slice(0, 3);
  for (const node of nodes) {
    if (doc.y > PH - 90) {
      doc.addPage();
      doc.y = 60;
    }

    // Hairline separator
    doc
      .moveTo(ML + 10, doc.y)
      .lineTo(ML + W, doc.y)
      .strokeColor(C.light)
      .lineWidth(0.4)
      .stroke();
    doc.moveDown(0.2);

    // HTML snippet (monospaced, truncated)
    const html = (node.html || '')
      .replace(/\s+/g, ' ')
      .trim()
      .slice(0, 140);

    doc
      .fillColor(C.body)
      .font('Courier')
      .fontSize(7.5)
      .text(html, ML + 14, doc.y, { width: W - 18 });

    // Failure summary (if present)
    if (node.failureSummary) {
      const summary = node.failureSummary
        .replace(/^Fix (any|all) of the following:\n?/i, '')
        .trim()
        .split('\n')
        .slice(0, 2)
        .join('; ');

      doc
        .fillColor(C.mid)
        .font('Helvetica-Oblique')
        .fontSize(8)
        .text(summary, ML + 14, doc.y + 2, { width: W - 18 });
    }

    doc.moveDown(0.55);
  }

  // "…and N more" tail
  if (rule.nodes.length > 3) {
    doc
      .fillColor(C.mid)
      .font('Helvetica-Oblique')
      .fontSize(8)
      .text(
        `…and ${rule.nodes.length - 3} more element${rule.nodes.length - 3 !== 1 ? 's' : ''}`,
        ML + 14,
      );
    doc.moveDown(0.35);
  }

  // Divider between rules
  doc.moveDown(0.5);
  doc
    .moveTo(ML, doc.y)
    .lineTo(ML + W, doc.y)
    .strokeColor('#f1f5f9')
    .lineWidth(0.5)
    .stroke();
  doc.moveDown(0.75);
}
