[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."analyse"]
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium", "axe-core"]
  timeout = 26
